# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_portable
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_portable)
  proxy_config = debug_portable
endif
ifeq ($(config),debug_x64)
  proxy_config = debug_x64
endif
ifeq ($(config),debug_avx)
  proxy_config = debug_avx
endif
ifeq ($(config),debug_avx2)
  proxy_config = debug_avx2
endif
ifeq ($(config),release_portable)
  proxy_config = release_portable
endif
ifeq ($(config),release_x64)
  proxy_config = release_x64
endif
ifeq ($(config),release_avx)
  proxy_config = release_avx
endif
ifeq ($(config),release_avx2)
  proxy_config = release_avx2
endif

PROJECTS := proxy

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

proxy:
ifneq (,$(proxy_config))
	@echo "==== Building proxy ($(proxy_config)) ===="
	@${MAKE} --no-print-directory -C . -f proxy.make config=$(proxy_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f proxy.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_portable"
	@echo "  debug_x64"
	@echo "  debug_avx"
	@echo "  debug_avx2"
	@echo "  release_portable"
	@echo "  release_x64"
	@echo "  release_avx"
	@echo "  release_avx2"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   proxy"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"